/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.JPSistemas.SistemaFuncionario.apresentacao;

import br.JPSistemas.SistemaFuncionario.entidade.Cargo;
import br.JPSistemas.SistemaFuncionario.entidade.Funcionario;
import br.JPSistemas.SistemaFuncionario.negocio.CargoBO;
import br.JPSistemas.SistemaFuncionario.negocio.FuncionarioBO;
import br.JPSistemas.SistemaFuncionario.negocio.ListaCargosVaziaException;
import br.JPSistemas.SistemaFuncionario.negocio.ListaFuncionariosVaziaException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author JOSIMAR
 */
public class TelaRelatorioCargoDepartamento extends javax.swing.JPanel implements AbaSelecionada {

    List<Cargo> cargos;

    /**
     * Creates new form TelaRelatorioFuncionarioCargo
     */
    public TelaRelatorioCargoDepartamento() {
        initComponents();
        cargos = new ArrayList<Cargo>();
    }

    @Override
    public void OnAbaSelecionada() {
        exibirDadosTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCargosDepartamento = new javax.swing.JTable();
        btnGerarRelatorio = new javax.swing.JButton();

        tblCargosDepartamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Departamento", "Cargo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCargosDepartamento);

        btnGerarRelatorio.setText("Gerar Relátorio PDF");
        btnGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnGerarRelatorio)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGerarRelatorio)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatorioActionPerformed
        try {
            String arquivoRelatorio = System.getProperty("user.dir") + "/relatorios/relatorioCargoDepartamento.jasper";
            Map<String, Object> parametros = new HashMap<String, Object>();
            JRBeanCollectionDataSource fonteDados = new JRBeanCollectionDataSource(this.cargos);
            JasperPrint relatorioGerado = JasperFillManager.fillReport(arquivoRelatorio, parametros, fonteDados);
            JasperViewer telaExibicaoRelatorio = new JasperViewer(relatorioGerado, false);
            telaExibicaoRelatorio.setTitle("Relatorio de Cargos");
            telaExibicaoRelatorio.setVisible(true);
        } catch (JRException e) {
            Logger.getLogger(TelaRelatorioCargoDepartamento.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this, "Erro ao exibir Relatório.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
// TODO add your handling code here:
// TODO add your handling code here:
    }//GEN-LAST:event_btnGerarRelatorioActionPerformed

    private void exibirDadosTabela() {
        try {
            this.carregarListaCargos();
            ModeloDadosFuncionarios modeloDadosFuncionarios = new ModeloDadosFuncionarios();
            this.tblCargosDepartamento.setModel(modeloDadosFuncionarios);
        } catch (ListaCargosVaziaException ex) {
            String titulo = "Lista de Cargos";
            String mensagem = "Lista de Cargos Vazia!";
            JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(TelaRelatorioCargoDepartamento.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            String titulo = "Erro ao Carregar Lista de Cargos!";
            String mensagem = "Ocorreu um erro inesperado, Favor entra em contato com o administrador";
            JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(TelaRelatorioCargoDepartamento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void carregarListaCargos() throws Exception {
        CargoBO cargoBO = new CargoBO();
        cargos = cargoBO.buscarTodos();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerarRelatorio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCargosDepartamento;
    // End of variables declaration//GEN-END:variables
class ModeloDadosFuncionarios extends AbstractTableModel {

        @Override
        public String getColumnName(int coluna) {
            if (coluna == 0) {
                return "Cargo";
            } else {
                return "Departamento";

            }
        }

        @Override
        public int getRowCount() {
            return cargos.size();
        }

        @Override
        public int getColumnCount() {
            return 2;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Cargo cargo = cargos.get(rowIndex);
            if (columnIndex == 0) {
                return cargo.getNome();
            } else {
                return cargo.getDepartamento().getArea();
            }
        }

    }

}
