/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.JPSistemas.SistemaFuncionario.apresentacao;

import br.JPSistemas.SistemaFuncionario.entidade.Cargo;
import br.JPSistemas.SistemaFuncionario.entidade.Departamento;
import br.JPSistemas.SistemaFuncionario.entidade.Diretor;
import br.JPSistemas.SistemaFuncionario.entidade.Gerente;
import br.JPSistemas.SistemaFuncionario.entidade.GraficoCargoFuncionario;
import br.JPSistemas.SistemaFuncionario.entidade.GraficoDepartamentoCargo;
import br.JPSistemas.SistemaFuncionario.negocio.CargoBO;
import br.JPSistemas.SistemaFuncionario.negocio.DepartamentoBO;
import br.JPSistemas.SistemaFuncionario.negocio.ListaCargosVaziaException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author JOSIMAR
 */
public class TelaInicial extends javax.swing.JFrame {

    TelaCadastroCargo telaCadastroCargo;
    TelaCadastroDepartamento telaCadastroDepartamento;
    TelaCadastroGerente telaCadastroGerente;
    TelaCadastroFuncionario telaCadastroFuncionario;
    TelaLogin telaLogin;
    TelaRelatorioFuncionarioCargo telaRelatorioFuncionarioCargo;
    TelaRelatorioCargoDepartamento telaRelatorioCargoDepartamento;
    TelaConsultaDepartamento telaConsultaDepartamento;
    TelaConsultaCargo telaConsultaCargo;
    TelaConsultaGerente telaConsultaGerente;
    public TelaConsultaFuncionario telaConsultaFuncionario;
    public Gerente gerente;
    public Diretor diretor;
    boolean sair;

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        this.resertCampos();
        sair = false;
    }

    public void resertCampos() {
        mnuConsulta.setVisible(false);
        mnuCadastro.setVisible(false);
        mnuRelatorios.setVisible(false);
        plnLogin.setVisible(false);
        mnuSair.setVisible(false);
        telaCadastroCargo = new TelaCadastroCargo();
        telaCadastroDepartamento = new TelaCadastroDepartamento();
        telaCadastroGerente = new TelaCadastroGerente(this);
        telaCadastroFuncionario = new TelaCadastroFuncionario();
        telaRelatorioFuncionarioCargo = new TelaRelatorioFuncionarioCargo();
        telaRelatorioCargoDepartamento = new TelaRelatorioCargoDepartamento();
        telaConsultaDepartamento = new TelaConsultaDepartamento(this);
        telaConsultaCargo = new TelaConsultaCargo(this);
        telaConsultaFuncionario = new TelaConsultaFuncionario(this);
        telaConsultaGerente = new TelaConsultaGerente(this);
        telaLogin = new TelaLogin(this);
        gerente = null;
        diretor = null;
        mnuSair.setVisible(false);
        mnuCadastroGerente.setVisible(true);
        mnuCadastroDepartamento.setVisible(true);
        mnuCadastroCargo.setVisible(true);
        mnuLogin.setVisible(true);
        mnuRelatoriosCargos.setVisible(true);
        mnuAlterarCargo.setVisible(true);
        mnuAlterarDepartamento.setVisible(true);
        mnuAlterarGerente.setVisible(true);
        this.setTitle("Sistema de Funcionários");
        sair = false;
        mnuGraficos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpPrincipal = new javax.swing.JTabbedPane();
        plnLogin = new javax.swing.JPanel();
        lbNomeLogin = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        mnuPrincipal = new javax.swing.JMenuBar();
        mnuUsuario = new javax.swing.JMenu();
        mnuLogin = new javax.swing.JMenuItem();
        mnuSair = new javax.swing.JMenuItem();
        mnuCadastro = new javax.swing.JMenu();
        mnuCadastroCargo = new javax.swing.JMenuItem();
        mnuCadastroFuncionario = new javax.swing.JMenuItem();
        mnuCadastroDepartamento = new javax.swing.JMenuItem();
        mnuCadastroGerente = new javax.swing.JMenu();
        mnuCadastrarGerente = new javax.swing.JMenuItem();
        mnuAlterarDadosGerente = new javax.swing.JMenuItem();
        mnuRelatorios = new javax.swing.JMenu();
        mnuRelatoriosFuncionarios = new javax.swing.JMenuItem();
        mnuRelatoriosCargos = new javax.swing.JMenuItem();
        mnuConsulta = new javax.swing.JMenu();
        mnuAlterarCargo = new javax.swing.JMenuItem();
        mnuAlterarDepartamento = new javax.swing.JMenuItem();
        mnuAlterarFuncionario = new javax.swing.JMenuItem();
        mnuAlterarGerente = new javax.swing.JMenuItem();
        mnuGraficos = new javax.swing.JMenu();
        munGraficoFuncionarioCargo = new javax.swing.JMenuItem();
        mnuGraficoCargoDepartamento = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Funcionários");
        setExtendedState(6);
        setFocusTraversalPolicyProvider(true);

        tpPrincipal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tpPrincipalStateChanged(evt);
            }
        });

        plnLogin.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuário"));

        lbNomeLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/JPSistemas/SistemaFuncionario/apresentacao/icones/status_online.png"))); // NOI18N
        lbNomeLogin.setText("Nome");

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/JPSistemas/SistemaFuncionario/apresentacao/icones/door_out.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plnLoginLayout = new javax.swing.GroupLayout(plnLogin);
        plnLogin.setLayout(plnLoginLayout);
        plnLoginLayout.setHorizontalGroup(
            plnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plnLoginLayout.createSequentialGroup()
                .addComponent(lbNomeLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair))
        );
        plnLoginLayout.setVerticalGroup(
            plnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plnLoginLayout.createSequentialGroup()
                .addComponent(lbNomeLogin)
                .addGap(0, 9, Short.MAX_VALUE))
            .addGroup(plnLoginLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        mnuPrincipal.setMaximumSize(new java.awt.Dimension(400, 32769));
        mnuPrincipal.setPreferredSize(new java.awt.Dimension(267, 30));

        mnuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/JPSistemas/SistemaFuncionario/apresentacao/icones/user.png"))); // NOI18N
        mnuUsuario.setText("Usuário");

        mnuLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/JPSistemas/SistemaFuncionario/apresentacao/icones/door_in.png"))); // NOI18N
        mnuLogin.setText("Login");
        mnuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLoginActionPerformed(evt);
            }
        });
        mnuUsuario.add(mnuLogin);

        mnuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/JPSistemas/SistemaFuncionario/apresentacao/icones/door_out.png"))); // NOI18N
        mnuSair.setText("Sair");
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        mnuUsuario.add(mnuSair);

        mnuPrincipal.add(mnuUsuario);

        mnuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/JPSistemas/SistemaFuncionario/apresentacao/icones/application_form_add.png"))); // NOI18N
        mnuCadastro.setText("Cadastro");

        mnuCadastroCargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/JPSistemas/SistemaFuncionario/apresentacao/icones/paste_plain.png"))); // NOI18N
        mnuCadastroCargo.setText("Cargo");
        mnuCadastroCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastroCargoActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuCadastroCargo);

        mnuCadastroFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/JPSistemas/SistemaFuncionario/apresentacao/icones/user_add.png"))); // NOI18N
        mnuCadastroFuncionario.setText("Funcionário");
        mnuCadastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastroFuncionarioActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuCadastroFuncionario);

        mnuCadastroDepartamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/JPSistemas/SistemaFuncionario/apresentacao/icones/chart_organisation_add.png"))); // NOI18N
        mnuCadastroDepartamento.setText("Departamento");
        mnuCadastroDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastroDepartamentoActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuCadastroDepartamento);

        mnuCadastroGerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/JPSistemas/SistemaFuncionario/apresentacao/icones/user_suit.png"))); // NOI18N
        mnuCadastroGerente.setText("Gerente");
        mnuCadastroGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastroGerenteActionPerformed(evt);
            }
        });

        mnuCadastrarGerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/JPSistemas/SistemaFuncionario/apresentacao/icones/add.png"))); // NOI18N
        mnuCadastrarGerente.setText("Cadastrar");
        mnuCadastrarGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastrarGerenteActionPerformed(evt);
            }
        });
        mnuCadastroGerente.add(mnuCadastrarGerente);

        mnuAlterarDadosGerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/JPSistemas/SistemaFuncionario/apresentacao/icones/action_refresh.gif"))); // NOI18N
        mnuAlterarDadosGerente.setText("Alterar Dados");
        mnuAlterarDadosGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAlterarDadosGerenteActionPerformed(evt);
            }
        });
        mnuCadastroGerente.add(mnuAlterarDadosGerente);

        mnuCadastro.add(mnuCadastroGerente);

        mnuPrincipal.add(mnuCadastro);

        mnuRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/JPSistemas/SistemaFuncionario/apresentacao/icones/file_acrobat.gif"))); // NOI18N
        mnuRelatorios.setText("Relatorios");

        mnuRelatoriosFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/JPSistemas/SistemaFuncionario/apresentacao/icones/file_acrobat.gif"))); // NOI18N
        mnuRelatoriosFuncionarios.setText("Relatorios de Funcionários por Cargo");
        mnuRelatoriosFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRelatoriosFuncionariosActionPerformed(evt);
            }
        });
        mnuRelatorios.add(mnuRelatoriosFuncionarios);

        mnuRelatoriosCargos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/JPSistemas/SistemaFuncionario/apresentacao/icones/file_acrobat.gif"))); // NOI18N
        mnuRelatoriosCargos.setText("Relatorios de Cargos por Departamento");
        mnuRelatoriosCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRelatoriosCargosActionPerformed(evt);
            }
        });
        mnuRelatorios.add(mnuRelatoriosCargos);

        mnuPrincipal.add(mnuRelatorios);

        mnuConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/JPSistemas/SistemaFuncionario/apresentacao/icones/application_view_list.png"))); // NOI18N
        mnuConsulta.setText("Consulta");

        mnuAlterarCargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/JPSistemas/SistemaFuncionario/apresentacao/icones/paste_plain.png"))); // NOI18N
        mnuAlterarCargo.setText("Cargos");
        mnuAlterarCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAlterarCargoActionPerformed(evt);
            }
        });
        mnuConsulta.add(mnuAlterarCargo);

        mnuAlterarDepartamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/JPSistemas/SistemaFuncionario/apresentacao/icones/chart_organisation.png"))); // NOI18N
        mnuAlterarDepartamento.setText("Departamentos");
        mnuAlterarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAlterarDepartamentoActionPerformed(evt);
            }
        });
        mnuConsulta.add(mnuAlterarDepartamento);

        mnuAlterarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/JPSistemas/SistemaFuncionario/apresentacao/icones/group.png"))); // NOI18N
        mnuAlterarFuncionario.setText("Funcionarios");
        mnuAlterarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAlterarFuncionarioActionPerformed(evt);
            }
        });
        mnuConsulta.add(mnuAlterarFuncionario);

        mnuAlterarGerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/JPSistemas/SistemaFuncionario/apresentacao/icones/users_suit.png"))); // NOI18N
        mnuAlterarGerente.setText("Gerentes");
        mnuAlterarGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAlterarGerenteActionPerformed(evt);
            }
        });
        mnuConsulta.add(mnuAlterarGerente);

        mnuPrincipal.add(mnuConsulta);

        mnuGraficos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/JPSistemas/SistemaFuncionario/apresentacao/icones/chart_pie.png"))); // NOI18N
        mnuGraficos.setText("Gráficos");

        munGraficoFuncionarioCargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/JPSistemas/SistemaFuncionario/apresentacao/icones/chart_pie.png"))); // NOI18N
        munGraficoFuncionarioCargo.setText("Gráfico de Funcionarios por Cargo");
        munGraficoFuncionarioCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                munGraficoFuncionarioCargoActionPerformed(evt);
            }
        });
        mnuGraficos.add(munGraficoFuncionarioCargo);

        mnuGraficoCargoDepartamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/JPSistemas/SistemaFuncionario/apresentacao/icones/chart_pie.png"))); // NOI18N
        mnuGraficoCargoDepartamento.setText("Gráfico de Cargos por Departamento");
        mnuGraficoCargoDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGraficoCargoDepartamentoActionPerformed(evt);
            }
        });
        mnuGraficos.add(mnuGraficoCargoDepartamento);

        mnuPrincipal.add(mnuGraficos);

        setJMenuBar(mnuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 337, Short.MAX_VALUE))
            .addComponent(tpPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLoginActionPerformed
        telaLogin.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuLoginActionPerformed

    public void resertTela() {
        this.resertCampos();
    }

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        // TODO add your handling code here:
        sair = true;
        tpPrincipal.removeAll();
        resertTela();
    }//GEN-LAST:event_mnuSairActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        sair = true;
        tpPrincipal.removeAll();
        resertTela();
// TODO add your handling code here:
    }//GEN-LAST:event_btnSairActionPerformed

    private void mnuCadastroCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastroCargoActionPerformed
        adicionarTab("Cadastro de Cargo", telaCadastroCargo);
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuCadastroCargoActionPerformed

    private void mnuCadastroDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastroDepartamentoActionPerformed
        adicionarTab("Cadastro de Departamento", telaCadastroDepartamento);
// TODO add your handling code here:
    }//GEN-LAST:event_mnuCadastroDepartamentoActionPerformed

    private void mnuCadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastroFuncionarioActionPerformed
        adicionarTab("Cadastro de Funcionário", telaCadastroFuncionario);

        // TODO add your handling code here:
    }//GEN-LAST:event_mnuCadastroFuncionarioActionPerformed

    private void tpPrincipalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tpPrincipalStateChanged
        if (sair != true) {
            AbaSelecionada abaSelecionada = (AbaSelecionada) tpPrincipal.getSelectedComponent();
            abaSelecionada.OnAbaSelecionada();
        }

// TODO add your handling code here:
    }//GEN-LAST:event_tpPrincipalStateChanged

    private void mnuRelatoriosFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRelatoriosFuncionariosActionPerformed
        adicionarTab("Relatorio de Funcionários", telaRelatorioFuncionarioCargo);
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuRelatoriosFuncionariosActionPerformed

    private void munGraficoFuncionarioCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_munGraficoFuncionarioCargoActionPerformed
        try {
            CargoBO cargoBO = new CargoBO();
            List<Cargo> cargos = cargoBO.buscarTodos();
            List<GraficoCargoFuncionario> graficoCargoFuncionarios = new ArrayList<GraficoCargoFuncionario>();
            for (int i = 0; i < cargos.size(); i++) {
                Cargo cargo = cargos.get(i);
                GraficoCargoFuncionario cargoFuncionario = new GraficoCargoFuncionario();
                cargoFuncionario.setNomeCargo(cargo.getNome());
                cargoFuncionario.setQuantidadefuncionarios(cargo.getFuncionarios().size());
                System.out.println(cargoFuncionario.getNomeCargo());
                System.out.println(cargoFuncionario.getQuantidadeFuncionarios());
                graficoCargoFuncionarios.add(cargoFuncionario);
            }
            String arquivoRelatorio = System.getProperty("user.dir") + "/relatorios/graficoFuncionarioCargo.jasper";
            Map<String, Object> parametros = new HashMap<String, Object>();
            JRBeanCollectionDataSource fonteDados = new JRBeanCollectionDataSource(graficoCargoFuncionarios);
            JasperPrint relatorioGerado = JasperFillManager.fillReport(arquivoRelatorio, parametros, fonteDados);
            JasperViewer telaExibicaoRelatorio = new JasperViewer(relatorioGerado, false);
            telaExibicaoRelatorio.setTitle("Gráfico de Cargos");
            telaExibicaoRelatorio.setVisible(true);
        } catch (JRException e) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this, "Erro ao exibir Gráfico.", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (ListaCargosVaziaException ex) {
            JOptionPane.showMessageDialog(this, "Lista de Cargos Vázia.", "Erro", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao exibir Gráfico.", "Erro", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_munGraficoFuncionarioCargoActionPerformed

    private void mnuRelatoriosCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRelatoriosCargosActionPerformed
        adicionarTab("Relatorio de Cargos", telaRelatorioCargoDepartamento);

// TODO add your handling code here:
    }//GEN-LAST:event_mnuRelatoriosCargosActionPerformed

    private void mnuAlterarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAlterarDepartamentoActionPerformed
        adicionarTab("Departamentos Cadastrados", telaConsultaDepartamento);
// TODO add your handling code here:
    }//GEN-LAST:event_mnuAlterarDepartamentoActionPerformed

    private void mnuAlterarCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAlterarCargoActionPerformed
        adicionarTab("Cargos Cadastrados", telaConsultaCargo);
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuAlterarCargoActionPerformed

    private void mnuAlterarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAlterarFuncionarioActionPerformed
        adicionarTab("Funcionarios Cadastrados", telaConsultaFuncionario);

// TODO add your handling code here:
    }//GEN-LAST:event_mnuAlterarFuncionarioActionPerformed

    private void mnuGraficoCargoDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGraficoCargoDepartamentoActionPerformed
        try {
            DepartamentoBO departamentoBO = new DepartamentoBO();
            List<Departamento> departamentos = departamentoBO.buscarTodos();
            List<GraficoDepartamentoCargo> graficoDepartamentoCargos = new ArrayList<GraficoDepartamentoCargo>();
            for (int i = 0; i < departamentos.size(); i++) {
                Departamento departamento = departamentos.get(i);
                GraficoDepartamentoCargo departamentoCargo = new GraficoDepartamentoCargo();
                departamentoCargo.setNomeDepartamento(departamento.getArea());
                departamentoCargo.setQuantidadeCargos(departamento.getCargos().size());
                graficoDepartamentoCargos.add(departamentoCargo);
            }
            String arquivoRelatorio = System.getProperty("user.dir") + "/relatorios/graficoCargoDepartamento.jasper";
            Map<String, Object> parametros = new HashMap<String, Object>();
            JRBeanCollectionDataSource fonteDados = new JRBeanCollectionDataSource(graficoDepartamentoCargos);
            JasperPrint relatorioGerado = JasperFillManager.fillReport(arquivoRelatorio, parametros, fonteDados);
            JasperViewer telaExibicaoRelatorio = new JasperViewer(relatorioGerado, false);
            telaExibicaoRelatorio.setTitle("Grafico de Departamentos");
            telaExibicaoRelatorio.setVisible(true);
        } catch (JRException e) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this, "Erro ao exibir Gráfico.", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (ListaCargosVaziaException ex) {
            JOptionPane.showMessageDialog(this, "Lista de Cargos Vázia.", "Erro", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao exibir Gráfico.", "Erro", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuGraficoCargoDepartamentoActionPerformed

    private void mnuAlterarGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAlterarGerenteActionPerformed
        adicionarTab("Gerentes Cadastrados", telaConsultaGerente);
    }//GEN-LAST:event_mnuAlterarGerenteActionPerformed

    private void mnuCadastrarGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastrarGerenteActionPerformed
        adicionarTab("Cadastro de Gerente", telaCadastroGerente);
    }//GEN-LAST:event_mnuCadastrarGerenteActionPerformed

    private void mnuAlterarDadosGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAlterarDadosGerenteActionPerformed
        TelaPesquisarCPF telaPesquisarCPF = new TelaPesquisarCPF(this);
        telaPesquisarCPF.setVisible(true);
    }//GEN-LAST:event_mnuAlterarDadosGerenteActionPerformed

    private void mnuCadastroGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastroGerenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuCadastroGerenteActionPerformed

    public void adicionarTab(String titulo, JPanel tela) {
        tpPrincipal.addTab(titulo, tela);
        tpPrincipal.setSelectedComponent(tela);
        tpPrincipal.setTabComponentAt(tpPrincipal.getSelectedIndex(), new ButtonTabComponent(tpPrincipal));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnSair;
    public javax.swing.JLabel lbNomeLogin;
    public javax.swing.JMenuItem mnuAlterarCargo;
    private javax.swing.JMenuItem mnuAlterarDadosGerente;
    public javax.swing.JMenuItem mnuAlterarDepartamento;
    private javax.swing.JMenuItem mnuAlterarFuncionario;
    public javax.swing.JMenuItem mnuAlterarGerente;
    private javax.swing.JMenuItem mnuCadastrarGerente;
    public javax.swing.JMenu mnuCadastro;
    public javax.swing.JMenuItem mnuCadastroCargo;
    public javax.swing.JMenuItem mnuCadastroDepartamento;
    private javax.swing.JMenuItem mnuCadastroFuncionario;
    public javax.swing.JMenu mnuCadastroGerente;
    public javax.swing.JMenu mnuConsulta;
    public javax.swing.JMenuItem mnuGraficoCargoDepartamento;
    public javax.swing.JMenu mnuGraficos;
    public javax.swing.JMenuItem mnuLogin;
    private javax.swing.JMenuBar mnuPrincipal;
    public javax.swing.JMenu mnuRelatorios;
    public javax.swing.JMenuItem mnuRelatoriosCargos;
    private javax.swing.JMenuItem mnuRelatoriosFuncionarios;
    public javax.swing.JMenuItem mnuSair;
    private javax.swing.JMenu mnuUsuario;
    private javax.swing.JMenuItem munGraficoFuncionarioCargo;
    public javax.swing.JPanel plnLogin;
    public javax.swing.JTabbedPane tpPrincipal;
    // End of variables declaration//GEN-END:variables
}
